"""
Base de conhecimento de ENTIDADES clínicas (diagnósticos, fármacos, exames, condutas).
Usada pelo motor local da IA para explicar cada alternativa: o que caracteriza a entidade
e quais pistas do enunciado a sustentam (ou estão ausentes).
Padrões em texto normalizado (minúsculo, sem acento).
"""

KB = [
    # ------------------------------------------------ PSIQUIATRIA
    {"p": r"agorafobia", "nome": "Agorafobia", "tipo": "dx",
     "resumo": "medo/evitação de situações das quais escapar seria difícil (sair de casa, multidões, transporte), frequentemente após ataques de pânico",
     "pistas": [r"medo de ter (uma )?crise", r"evit", r"sair de casa|fora do apartamento|em publico", r"ataque|crise"]},
    {"p": r"ansiedade generalizada|\btag\b", "nome": "Transtorno de ansiedade generalizada", "tipo": "dx",
     "resumo": "preocupação excessiva e difusa sobre vários temas por ≥ 6 meses, com tensão, insônia e fadiga – sem crises paroxísticas",
     "pistas": [r"preocupac", r"6 meses", r"tensao muscular", r"insonia"]},
    {"p": r"ansiedade social|fobia social", "nome": "Fobia social", "tipo": "dx",
     "resumo": "medo de avaliação negativa em situações sociais/de desempenho", "pistas": [r"julgad|avaliad|constrang|falar em publico"]},
    {"p": r"panico", "nome": "Transtorno de pânico", "tipo": "dx",
     "resumo": "ataques de pânico recorrentes e inesperados + preocupação persistente com novos ataques",
     "pistas": [r"palpita", r"sensacao de morte|iria morrer", r"subit", r"sudorese"]},
    {"p": r"depress", "nome": "Transtorno depressivo", "tipo": "dx",
     "resumo": "humor deprimido e/ou anedonia por ≥ 2 semanas com sintomas neurovegetativos", "pistas": [r"anedonia", r"humor deprimido", r"insonia", r"apetite"]},
    {"p": r"sintomas somaticos", "nome": "Transtorno de sintomas somáticos", "tipo": "dx",
     "resumo": "sintomas físicos com pensamentos/comportamentos desproporcionais sobre eles", "pistas": [r"multiplas queixas", r"consultas repetidas"]},
    {"p": r"hipocondria|ansiedade de doenca", "nome": "Transtorno de ansiedade de doença", "tipo": "dx",
     "resumo": "preocupação em ter doença grave com poucos ou nenhum sintoma", "pistas": [r"medo de ter (uma )?doenca", r"exames normais"]},
    {"p": r"mirtazapina", "nome": "Mirtazapina", "tipo": "farmaco",
     "resumo": "antidepressivo sedativo e orexígeno – útil com insônia e perda de apetite/peso", "pistas": [r"insonia", r"perda de peso|apetite"]},
    {"p": r"bupropiona", "nome": "Bupropiona", "tipo": "farmaco",
     "resumo": "antidepressivo sem ganho de peso ou disfunção sexual; reduz limiar convulsivo; auxilia cessação do tabagismo", "pistas": [r"tabag", r"disfuncao sexual"]},
    {"p": r"buspirona", "nome": "Buspirona", "tipo": "farmaco",
     "resumo": "ansiolítico agonista 5-HT1A para TAG, sem dependência e sem sedação (início lento)", "pistas": [r"dependencia", r"preocupac"]},
    {"p": r"clonazepam|alprazolam|diazepam|benzodiazep|temazepam", "nome": "Benzodiazepínico", "tipo": "farmaco",
     "resumo": "ansiolítico/hipnótico de ação rápida, com risco de dependência, tolerância, quedas e sedação – uso curto", "pistas": [r"crise aguda", r"convuls"]},
    {"p": r"\blitio\b", "nome": "Lítio", "tipo": "farmaco",
     "resumo": "estabilizador de humor com janela estreita; toxicidade com AINE, IECA, tiazídico e desidratação (tremor grosseiro, ataxia, confusão)",
     "pistas": [r"bipolar", r"ibuprofeno|aine|anti-inflamatorio", r"tremor", r"ataxia|confus"]},
    {"p": r"clonidina", "nome": "Clonidina", "tipo": "farmaco",
     "resumo": "agonista alfa-2 central: tiques/Tourette, TDAH (adjuvante), abstinência; anti-hipertensivo com rebote", "pistas": [r"tique", r"tourette"]},

    # ------------------------------------------------ CARDIO / PULMÃO
    {"p": r"dieta dash|padrao alimentar dash", "nome": "Dieta DASH", "tipo": "conduta",
     "resumo": "intervenção não farmacológica de maior impacto na PA (rica em frutas, vegetais, laticínios magros; pobre em sódio)", "pistas": [r"pressao arterial", r"1(2|3)\d x"]},
    {"p": r"tiazid|hidroclorotiazida|clortalidona", "nome": "Diurético tiazídico", "tipo": "farmaco",
     "resumo": "anti-hipertensivo de 1ª linha; efeitos adversos: hipocalemia, hiponatremia, hiperuricemia (gota), hiperglicemia", "pistas": [r"hipertens"]},
    {"p": r"\bieca\b|enalapril|captopril|lisinopril", "nome": "IECA", "tipo": "farmaco",
     "resumo": "anti-hipertensivo com proteção renal (DM, proteinúria) e na IC; contraindicado na gestação; causa tosse e hipercalemia",
     "pistas": [r"diabet", r"proteinuria|albuminuria", r"insuficiencia cardiaca"]},
    {"p": r"espironolactona", "nome": "Espironolactona", "tipo": "farmaco",
     "resumo": "antagonista mineralocorticoide – reduz mortalidade na IC com FE reduzida; HAS resistente; atenção à hipercalemia",
     "pistas": [r"fracao de ejecao|fe(ve)? de \d", r"b3", r"dispneia", r"resistente"]},
    {"p": r"pericardiocentese|janela pericardica", "nome": "Pericardiocentese / janela pericárdica", "tipo": "conduta",
     "resumo": "tratamento imediato do tamponamento cardíaco (tríade de Beck: hipotensão, turgência jugular, bulhas abafadas)",
     "pistas": [r"bulhas abafadas", r"turgencia|estase jugular|distensao venosa jugular", r"pulso paradoxal", r"derrame pericardico", r"hipotens|pa .?[5-8]\d x"]},
    {"p": r"descompressao|toracocentese de alivio|puncao de alivio", "nome": "Descompressão torácica", "tipo": "conduta",
     "resumo": "conduta imediata no pneumotórax hipertensivo (desvio de traqueia, MV abolido, hipertimpanismo, choque)",
     "pistas": [r"desvio (de )?traque", r"hipertimpan", r"murmurio .*abolido|ausencia de murmurio"]},
    {"p": r"toracostomia|drenagem (pleural|toracica)|dreno de torax", "nome": "Drenagem torácica (toracostomia)", "tipo": "conduta",
     "resumo": "tratamento de hemotórax e pneumotórax (após descompressão, se hipertensivo)",
     "pistas": [r"macicez", r"hemotorax|pneumotorax", r"murmurio .*(abolido|ausente|diminuido)", r"liquido .*pleura"]},
    {"p": r"cardioversao eletrica|choque sincronizado", "nome": "Cardioversão elétrica", "tipo": "conduta",
     "resumo": "taquiarritmia com instabilidade hemodinâmica", "pistas": [r"instab|hipotens|rebaixamento", r"taquicardia|fibrilacao|flutter"]},
    {"p": r"espirometria", "nome": "Espirometria", "tipo": "exame",
     "resumo": "confirma obstrução (VEF1/CVF < 0,70 pós-BD na DPOC) e diferencia padrões obstrutivo e restritivo",
     "pistas": [r"tabag|macos", r"dispneia", r"tosse cronica|tosse"]},
    {"p": r"ecocardiogram", "nome": "Ecocardiograma", "tipo": "exame",
     "resumo": "avalia função ventricular, valvas, pericárdio e shunts (com microbolhas pesquisa forame oval patente)",
     "pistas": [r"sopro", r"insuficiencia cardiaca|fracao de ejecao", r"avc|acidente vascular", r"derrame pericardico"]},
    {"p": r"cateterismo|cineangiocoronariografia", "nome": "Cateterismo cardíaco", "tipo": "exame",
     "resumo": "exame invasivo para doença coronariana – indicado em SCA de alto risco ou isquemia comprovada", "pistas": [r"supra|infarto|angina|troponina"]},
    {"p": r"angiotomografia|angio-?tc", "nome": "Angiotomografia", "tipo": "exame",
     "resumo": "imagem vascular com contraste (TEP, dissecção, oclusões) – exige estabilidade e função renal adequada", "pistas": [r"embolia|tep|dissec|oclus"]},
    {"p": r"salbutamol|albuterol|beta-?2", "nome": "Beta-2 agonista de curta ação", "tipo": "farmaco",
     "resumo": "broncodilatador de resgate – broncoespasmo agudo (asma, exposição a irritantes)", "pistas": [r"sibil", r"broncoespasmo|asma", r"tempo expiratorio"]},
    {"p": r"intubacao", "nome": "Intubação orotraqueal", "tipo": "conduta",
     "resumo": "indicada por falência respiratória, Glasgow ≤ 8, incapacidade de proteger via aérea ou via aérea ameaçada",
     "pistas": [r"glasgow (de )?[3-8]\b", r"rebaixamento", r"satura.*[5-7]\d ?%", r"estridor|queimadura de face"]},

    # ------------------------------------------------ ENDÓCRINO
    {"p": r"insulina", "nome": "Insulinoterapia", "tipo": "farmaco",
     "resumo": "indicada na deficiência insulínica (DM1/LADA), sintomas catabólicos, cetose, HbA1c muito alta, gestação e CAD",
     "pistas": [r"perda de peso|emagrec", r"poliuria|polidipsia", r"cetonuria|cetose|cetoacidose", r"hba1c .*1\d"]},
    {"p": r"metformina", "nome": "Metformina", "tipo": "farmaco",
     "resumo": "1ª linha no DM2 sem contraindicação (TFG < 30); não causa hipoglicemia; perda de peso neutra/discreta", "pistas": [r"diabetes (mellitus )?tipo 2|dm2", r"obes|sobrepeso|imc (de )?(2[7-9]|3\d)"]},
    {"p": r"glibenclamida|gliburida|sulfonilureia|glicazida", "nome": "Sulfonilureia", "tipo": "farmaco",
     "resumo": "secretagogo de insulina – risco de hipoglicemia e ganho de peso; exige reserva pancreática", "pistas": []},
    {"p": r"levotiroxina", "nome": "Levotiroxina", "tipo": "farmaco",
     "resumo": "reposição no hipotireoidismo (TSH alto, T4 livre baixo); no congênito iniciar imediatamente", "pistas": [r"tsh .*(elevad|alto|\d{2})", r"t4 livre (baixo|diminu)"]},
    {"p": r"metanefrina|catecolamina", "nome": "Metanefrinas plasmáticas/urinárias", "tipo": "exame",
     "resumo": "triagem de feocromocitoma (crises de cefaleia, palpitação, sudorese com hipertensão)", "pistas": [r"cefaleia", r"palpita", r"sudorese", r"crise hipertens|pa .*2\d\d"]},
    {"p": r"tireotoxicose|hipertireoid|graves", "nome": "Tireotoxicose", "tipo": "dx",
     "resumo": "excesso de hormônio tireoidiano: perda de peso com apetite preservado, taquicardia, tremor, intolerância ao calor, diarreia",
     "pistas": [r"perda de peso", r"tremor", r"calor", r"taquicard|fc 1\d\d", r"bocio|tireoide"]},
    {"p": r"tireoidite subaguda|de quervain", "nome": "Tireoidite subaguda (De Quervain)", "tipo": "dx",
     "resumo": "pós-viral, tireoide dolorosa, VHS alto, tireotoxicose transitória com captação de iodo baixa", "pistas": [r"dor .*pescoco|tireoide dolorosa", r"vhs", r"captacao"]},
    {"p": r"feocromocitoma", "nome": "Feocromocitoma", "tipo": "dx",
     "resumo": "tumor secretor de catecolaminas: crises de cefaleia, palpitação e sudorese com hipertensão", "pistas": [r"cefaleia", r"palpita", r"sudorese"]},
    {"p": r"cushing", "nome": "Síndrome de Cushing", "tipo": "dx",
     "resumo": "hipercortisolismo: obesidade central, estrias violáceas, fragilidade capilar, miopatia proximal, HAS, hiperglicemia", "pistas": [r"estrias", r"obesidade central|giba"]},
    {"p": r"addison|insuficiencia adrenal", "nome": "Insuficiência adrenal", "tipo": "dx",
     "resumo": "fadiga, hipotensão, hiperpigmentação, hiponatremia e hipercalemia", "pistas": [r"hiperpigment", r"hipotens", r"hiponatrem"]},
    {"p": r"carcinoide", "nome": "Síndrome carcinoide", "tipo": "dx",
     "resumo": "flushing, diarreia e broncoespasmo por serotonina (metástase hepática de tumor neuroendócrino)", "pistas": [r"rubor|flushing", r"diarreia", r"sibil"]},

    # ------------------------------------------------ INFECTO / NEFRO / HEMATO
    {"p": r"carga viral|rna do hiv|pcr .*hiv", "nome": "Carga viral do HIV (RNA)", "tipo": "exame",
     "resumo": "detecta infecção aguda pelo HIV na janela imunológica, quando a sorologia ainda pode ser negativa", "pistas": [r"relacao sexual|exposicao", r"febre", r"exantema", r"linfonod"]},
    {"p": r"penicilina", "nome": "Penicilina", "tipo": "farmaco",
     "resumo": "tratamento da sífilis (benzatina) e profilaxia na anemia falciforme (oral) e febre reumática", "pistas": [r"sifilis|vdrl", r"falciforme|hb ?ss", r"faringit|amigdal"]},
    {"p": r"azitromicina", "nome": "Azitromicina", "tipo": "farmaco",
     "resumo": "macrolídeo: coqueluche, clamídia, PAC atípica", "pistas": [r"guincho|paroxis|coqueluche", r"clamidia|uretrite|cervicite"]},
    {"p": r"sulfametoxazol|trimetoprima|cotrimoxazol", "nome": "Sulfametoxazol-trimetoprima", "tipo": "farmaco",
     "resumo": "pode causar agranulocitose, hipercalemia, reações cutâneas graves; profilaxia de pneumocistose", "pistas": [r"neutrofil|leucocit|agranulocit", r"cd4"]},
    {"p": r"solucao salina hipertonica|nacl 3|salina a 3", "nome": "Salina hipertônica 3%", "tipo": "conduta",
     "resumo": "hiponatremia aguda sintomática grave (convulsão, rebaixamento) – bolus para elevar Na em 4–6 mEq/L", "pistas": [r"sodio .*1[01]\d|hiponatrem", r"convuls|crise|rebaixamento"]},
    {"p": r"osmolalidade|osmolaridade", "nome": "Osmolalidade plasmática/urinária", "tipo": "exame",
     "resumo": "primeiro passo na investigação da hiponatremia (confirma hipotonicidade e diferencia SIADH de polidipsia)", "pistas": [r"sodio|hiponatrem", r"euvolem|sem edema"]},
    {"p": r"rabdomiolise|lesao renal aguda|injuria renal aguda|necrose tubular", "nome": "Lesão renal aguda", "tipo": "dx",
     "resumo": "complicação temida da rabdomiólise, sepse, nefrotóxicos e hipovolemia", "pistas": [r"cpk|creatinoquinase|creatina", r"urina escura|coca", r"imobil"]},
    {"p": r"leucemia mieloide cronica|\blmc\b", "nome": "Leucemia mieloide crônica", "tipo": "dx",
     "resumo": "leucocitose com todas as fases de maturação, basofilia, esplenomegalia e cromossomo Philadelphia t(9;22)", "pistas": [r"basofil", r"esplenomegal", r"philadelphia|bcr-?abl|t\(9;22\)"]},
    {"p": r"leucemia linfo(cit|bl)ica aguda|\blla\b", "nome": "Leucemia linfoblástica aguda", "tipo": "dx",
     "resumo": "mais comum na infância; blastos, citopenias, dor óssea, linfonodomegalia", "pistas": [r"blasto", r"crianca|menino|menina", r"dor ossea"]},
    {"p": r"leucemia mieloide aguda|\blma\b", "nome": "Leucemia mieloide aguda", "tipo": "dx",
     "resumo": "adultos, blastos mieloides > 20%, bastonetes de Auer, citopenias", "pistas": [r"blasto", r"auer"]},
    {"p": r"leucemia linfocitica cronica|\bllc\b", "nome": "Leucemia linfocítica crônica", "tipo": "dx",
     "resumo": "idoso com linfocitose madura e manchas de Gumprecht", "pistas": [r"linfocitose", r"idos"]},

    # ------------------------------------------------ GI / CIRURGIA
    {"p": r"endoscopia digestiva alta|\beda\b|esofagogastroduodenoscopia|endoscopia", "nome": "Endoscopia digestiva alta", "tipo": "exame",
     "resumo": "exame de escolha para dispepsia com sinais de alarme e HDA (diagnóstica e terapêutica)",
     "pistas": [r"hematemese|melena", r"perda de peso|emagrec", r"anemia", r"disfagia", r"vomit"]},
    {"p": r"colonoscopia", "nome": "Colonoscopia", "tipo": "exame",
     "resumo": "diagnóstico (com biópsia) de neoplasia colorretal e investigação de HDB; rastreio a partir de 45–50 anos",
     "pistas": [r"sangue .*fezes|hematoquezia|enterorragia|sangramento (retal|anal)", r"habito intestinal", r"anemia", r"emagrec"]},
    {"p": r"tomografia", "nome": "Tomografia computadorizada", "tipo": "exame",
     "resumo": "imagem de alta acurácia – exige paciente estável; padrão-ouro em trauma abdominal estável, apendicite duvidosa no adulto",
     "pistas": [r"estavel|pa (normal|1[1-4]\d)", r"trauma", r"duvida"]},
    {"p": r"ultrassonografia|ultrassom|\busg\b|ecografia", "nome": "Ultrassonografia", "tipo": "exame",
     "resumo": "exame inicial barato, sem radiação: vesícula, rins, pelve feminina, gestação, crianças; FAST no trauma",
     "pistas": [r"gestant|gestac", r"crianca|lactente", r"vesicul|biliar|colica", r"retencao|bexiga"]},
    {"p": r"laparotomia", "nome": "Laparotomia exploradora", "tipo": "conduta",
     "resumo": "trauma abdominal com instabilidade + FAST positivo, peritonite ou evisceração", "pistas": [r"instab|choque|hipotens", r"peritonit|evisc|fast positivo"]},
    {"p": r"apendicectomia", "nome": "Apendicectomia", "tipo": "conduta",
     "resumo": "tratamento da apendicite aguda", "pistas": [r"fossa iliaca direita|mcburney", r"blumberg"]},
    {"p": r"desbridamento", "nome": "Desbridamento cirúrgico", "tipo": "conduta",
     "resumo": "remoção de tecido desvitalizado – fratura exposta, fasciíte necrosante, feridas contaminadas", "pistas": [r"exposta|necros|desvitaliz|contamin"]},
    {"p": r"observacao|expectante|nenhum(a)? (exame|intervencao|investigacao|conduta)|nao (ha|e) necessari", "nome": "Conduta expectante / nenhuma intervenção", "tipo": "conduta",
     "resumo": "correta quando o quadro é fisiológico/benigno, autolimitado e o paciente está estável",
     "pistas": [r"estavel", r"sinais vitais normais|dentro dos limites", r"assintomatic|sente-se bem", r"melhora"]},
    {"p": r"orquidopexia|exploracao escrotal|exploracao cirurgica", "nome": "Exploração cirúrgica escrotal", "tipo": "conduta",
     "resumo": "torção testicular – não atrasar com exames", "pistas": [r"dor (escrotal|testicular) subita", r"cremaster", r"horizontaliz"]},

    # ------------------------------------------------ GO / PEDIATRIA
    {"p": r"imunoglobulina anti-?d|rhogam|rho\(d\)", "nome": "Imunoglobulina anti-D", "tipo": "farmaco",
     "resumo": "gestante Rh negativo não sensibilizada (Coombs indireto negativo): com 28 semanas e até 72h pós-parto", "pistas": [r"rh negativ|negativo", r"coombs .*negativ"]},
    {"p": r"sulfato de magnesio", "nome": "Sulfato de magnésio", "tipo": "farmaco",
     "resumo": "prevenção/tratamento de eclâmpsia na pré-eclâmpsia com sinais de gravidade; neuroproteção fetal < 32 sem", "pistas": [r"pre-?eclamps|eclamps", r"cefaleia|escotomas|epigastralgia"]},
    {"p": r"toque vaginal", "nome": "Toque vaginal", "tipo": "exame",
     "resumo": "contraindicado antes de USG se suspeita de placenta prévia (sangramento indolor no 3º trimestre)", "pistas": [r"sangramento .*indolor"]},
    {"p": r"dicloxacilina|cefalexina|oxacilina", "nome": "Antibiótico anti-estafilocócico", "tipo": "farmaco",
     "resumo": "mastite puerperal, celulite e impetigo (S. aureus)", "pistas": [r"mama|mastite|puerper", r"celulite|eritema"]},
    {"p": r"fsh|foliculo-?estimulante", "nome": "Dosagem de FSH", "tipo": "exame",
     "resumo": "FSH elevado confirma falência ovariana (menopausa/IOP)", "pistas": [r"fogach|ondas de calor", r"irregularidade menstrual|amenorre"]},
    {"p": r"biopsia", "nome": "Biópsia", "tipo": "exame",
     "resumo": "diagnóstico histológico definitivo de lesões suspeitas (neoplasia)", "pistas": [r"lesao|nodulo|massa|ulcera", r"suspeit", r"endurec"]},
    {"p": r"dexametasona", "nome": "Dexametasona", "tipo": "farmaco",
     "resumo": "corticoide: crupe viral (dose única), meningite bacteriana, edema cerebral tumoral, maturação pulmonar fetal", "pistas": [r"estridor|tosse ladrante|crupe"]},
    {"p": r"epinefrina|adrenalina", "nome": "Adrenalina", "tipo": "farmaco",
     "resumo": "anafilaxia (IM), PCR, crupe com estridor em repouso (nebulizada)", "pistas": [r"estridor", r"anafila|urticaria .*hipotens"]},
    {"p": r"idade ossea|maos e punho", "nome": "Radiografia para idade óssea", "tipo": "exame",
     "resumo": "exame inicial na baixa estatura: diferencia baixa estatura familiar (IO = IC) de atraso constitucional (IO atrasada)", "pistas": [r"baixa estatura|percentil", r"crescimento"]},
    {"p": r"corticoster|prednison|metilprednisolona|corticoide", "nome": "Corticoide", "tipo": "farmaco",
     "resumo": "anti-inflamatório/imunossupressor: síndrome nefrótica da criança, asma/DPOC exacerbados, doenças autoimunes; intralesional no queloide",
     "pistas": [r"edema palpebral|proteinuria", r"exacerba", r"queloide"]},
    {"p": r"notificac", "nome": "Notificação compulsória", "tipo": "conduta",
     "resumo": "obrigatória diante de suspeita de doenças da lista nacional e de violência (criança, idoso, mulher)", "pistas": [r"suspeita", r"maus-?tratos|negligencia|violencia|equimoses"]},
    {"p": r"autonomia|decisao .* (do|da) paciente|cabe .* paciente", "nome": "Respeito à autonomia", "tipo": "conduta",
     "resumo": "paciente capaz e informado decide sobre o próprio tratamento, inclusive recusa", "pistas": [r"lucid|consciente|orientad|capaz", r"recusa"]},
    {"p": r"cuidados paliativos|paliativ", "nome": "Cuidados paliativos", "tipo": "conduta",
     "resumo": "foco em conforto e qualidade de vida em doença avançada/terminal, respeitando diretivas antecipadas", "pistas": [r"metasta|terminal|estagio iv|avancad", r"diretivas"]},
]

KB += [
    # ------------------------------------------------ FÁRMACOS FREQUENTES
    {"p": r"furosemida|diuretico de alca", "nome": "Diurético de alça (furosemida)", "tipo": "farmaco",
     "resumo": "alivia congestão (edema agudo de pulmão, IC descompensada, hipervolemia); piora hipovolemia e IAM de VD", "pistas": [r"estertores|crepita", r"edema", r"congest|dispneia"]},
    {"p": r"nitrato|nitroglicerina|isossorbida", "nome": "Nitrato", "tipo": "farmaco",
     "resumo": "vasodilatador venoso – angina/SCA e edema agudo de pulmão; contraindicado em hipotensão, IAM de VD e uso de inibidor de PDE-5", "pistas": [r"dor precordial|angina", r"congest"]},
    {"p": r"nitroprussiato", "nome": "Nitroprussiato", "tipo": "farmaco",
     "resumo": "vasodilatador IV potente para emergência hipertensiva (dissecção, EAP) – exige PA elevada", "pistas": [r"2\d\d ?x ?1\d\d", r"emergencia hipertensiva|dissec"]},
    {"p": r"betabloq|metoprolol|propranolol|atenolol|carvedilol|bisoprolol|esmolol", "nome": "Betabloqueador", "tipo": "farmaco",
     "resumo": "controle de FC, angina, IC crônica com FE reduzida, profilaxia de varizes (não seletivo); contraindicado em choque, bradicardia, asma grave, cocaína aguda", "pistas": [r"taquicard|palpita", r"angina|infarto", r"tremor|tireotox"]},
    {"p": r"expansao volemica|reposicao volemica|cristaloide|soro fisiologico|ringer|cloreto de sodio 0,9|solucao salina", "nome": "Expansão volêmica com cristaloide", "tipo": "conduta",
     "resumo": "primeira medida na hipovolemia/choque hemorrágico e séptico e no IAM de VD com hipotensão", "pistas": [r"hipotens|choque|pa .*(cai|[5-8]\d ?x)", r"desidrat|vomit|diarre", r"taquicard", r"extremidades frias|perfusao"]},
    {"p": r"amiodarona", "nome": "Amiodarona", "tipo": "farmaco",
     "resumo": "antiarrítmico para FV/TV sem pulso refratária e controle de ritmo; toxicidade tireoidiana, pulmonar e hepática", "pistas": [r"fibrilacao|taquicardia ventricular"]},
    {"p": r"adenosina", "nome": "Adenosina", "tipo": "farmaco",
     "resumo": "taquicardia supraventricular estável após manobra vagal", "pistas": [r"taquicardia supraventricular|qrs estreito"]},
    {"p": r"heparina|enoxaparina|anticoagula|varfarina|rivaroxabana|apixabana|dabigatrana", "nome": "Anticoagulação", "tipo": "farmaco",
     "resumo": "TEV (TVP/TEP), FA com CHA2DS2-VASc elevado, isquemia arterial aguda; contraindicada com sangramento ativo", "pistas": [r"trombose|tvp|embolia|tep", r"fibrilacao atrial", r"edema (unilateral|de panturrilha)"]},
    {"p": r"trombolis|alteplase|tenecteplase|estreptoquinase|fibrinolit", "nome": "Trombólise", "tipo": "conduta",
     "resumo": "AVC isquêmico até 4,5h, IAM com supra sem angioplastia disponível em tempo, TEP com instabilidade", "pistas": [r"supra|supradesnivel", r"deficit|hemiparesia|afasia", r"instab"]},
    {"p": r"angioplastia", "nome": "Angioplastia primária", "tipo": "conduta",
     "resumo": "reperfusão preferencial no IAM com supra de ST (porta-balão ≤ 90–120 min)", "pistas": [r"supra|supradesnivel"]},
    {"p": r"\baas\b|acido acetilsalicilico|aspirina", "nome": "AAS", "tipo": "farmaco",
     "resumo": "antiagregante – SCA, prevenção secundária cardiovascular, pré-eclâmpsia (profilaxia em alto risco); evitar na dengue e em crianças (Reye)", "pistas": [r"dor precordial|infarto|angina", r"pre-?eclamps"]},
    {"p": r"estatina|sinvastatina|atorvastatina|rosuvastatina", "nome": "Estatina", "tipo": "farmaco",
     "resumo": "redução de LDL e de eventos cardiovasculares (prevenção secundária, DM 40–75 anos, alto risco)", "pistas": [r"ldl|colesterol", r"diabet", r"infarto|avc"]},
    {"p": r"ceftriaxona|cefotaxima", "nome": "Ceftriaxona", "tipo": "farmaco",
     "resumo": "cefalosporina de 3ª geração: meningite, PAC grave, gonorreia, PBE, pielonefrite, profilaxia na HDA do cirrótico", "pistas": [r"rigidez de nuca|meningit", r"febre", r"cirro"]},
    {"p": r"amoxicilina", "nome": "Amoxicilina", "tipo": "farmaco",
     "resumo": "1ª escolha em OMA, sinusite e faringite bacterianas e PAC ambulatorial sem comorbidade", "pistas": [r"otite|otalgia|timpan", r"amigdal|faring", r"pneumonia"]},
    {"p": r"metronidazol", "nome": "Metronidazol", "tipo": "farmaco",
     "resumo": "anaeróbios, vaginose bacteriana, tricomoníase, giardíase, amebíase, C. difficile (alternativa)", "pistas": [r"corrimento|odor|peixe", r"diarre"]},
    {"p": r"doxiciclina", "nome": "Doxiciclina", "tipo": "farmaco",
     "resumo": "clamídia, DIP (associada), leptospirose leve, riquetsioses, doença de Lyme; evitar em gestantes e < 8 anos", "pistas": [r"carrapato|enchente|rato"]},
    {"p": r"fluconazol|nistatina|miconazol|clotrimazol|antifungico", "nome": "Antifúngico", "tipo": "farmaco",
     "resumo": "candidíase (vulvovaginal, oral) e outras micoses", "pistas": [r"grumos|prurido vulvar|placas brancas"]},
    {"p": r"aciclovir|valaciclovir", "nome": "Aciclovir", "tipo": "farmaco",
     "resumo": "herpes simples/zóster, encefalite herpética, varicela em risco", "pistas": [r"vesicul|herpes|zoster|dermatomo"]},
    {"p": r"oseltamivir", "nome": "Oseltamivir", "tipo": "farmaco",
     "resumo": "influenza em grupos de risco ou síndrome respiratória aguda grave, idealmente em até 48h", "pistas": [r"gripe|influenza|srag"]},
    {"p": r"vancomicina", "nome": "Vancomicina", "tipo": "farmaco",
     "resumo": "gram-positivos resistentes (MRSA), C. difficile (via oral)", "pistas": [r"mrsa|resistente"]},
    {"p": r"sertralina|fluoxetina|escitalopram|citalopram|paroxetina|\bisrs\b|inibidor seletivo", "nome": "ISRS", "tipo": "farmaco",
     "resumo": "1ª linha em depressão, TAG, pânico, TOC e TEPT; efeitos: disfunção sexual, náuseas, síndrome serotoninérgica se associados", "pistas": [r"anedonia|humor", r"ansied|panico|preocupac"]},
    {"p": r"haloperidol|risperidona|olanzapina|quetiapina|antipsicot", "nome": "Antipsicótico", "tipo": "farmaco",
     "resumo": "psicose, agitação, delirium hiperativo (baixa dose); efeitos extrapiramidais, síndrome neuroléptica maligna", "pistas": [r"alucina|delir|agita"]},
    {"p": r"naloxona", "nome": "Naloxona", "tipo": "farmaco",
     "resumo": "reversão de intoxicação por opioide (miose, bradipneia, rebaixamento)", "pistas": [r"miose", r"bradipneia|fr [4-9]\b", r"opioide|morfina|heroina"]},
    {"p": r"omeprazol|pantoprazol|\bibp\b|inibidor de bomba", "nome": "Inibidor de bomba de prótons", "tipo": "farmaco",
     "resumo": "DRGE, úlcera péptica, erradicação de H. pylori (associado), HDA não varicosa", "pistas": [r"pirose|azia|dispepsi|epigastr"]},
    {"p": r"ocitocina", "nome": "Ocitocina", "tipo": "farmaco",
     "resumo": "manejo ativo do 3º período (prevenção de HPP), 1ª droga na atonia uterina, indução/condução do parto", "pistas": [r"hemorragia pos-?parto|atonia|utero amolecido"]},
    {"p": r"misoprostol", "nome": "Misoprostol", "tipo": "farmaco",
     "resumo": "preparo de colo/indução, esvaziamento uterino no abortamento, HPP (adjuvante)", "pistas": [r"abort|obito fetal|colo desfavoravel"]},
    {"p": r"metotrexato", "nome": "Metotrexato", "tipo": "farmaco",
     "resumo": "gravidez ectópica íntegra/pequena com beta-hCG baixo (estável) e âncora da artrite reumatoide", "pistas": [r"ectopic|beta-?hcg", r"poliartrit|artrite reumatoide"]},
    {"p": r"cesarea|cesariana", "nome": "Cesárea", "tipo": "conduta",
     "resumo": "sofrimento fetal com parto não iminente, placenta prévia total, apresentação anômala, DPP com feto vivo sem parto iminente, iteratividade", "pistas": [r"sofrimento fetal|bradicardia fetal|desaceleraca", r"placenta previa", r"pelvic"]},
    {"p": r"soro de reidratacao|\bsro\b|terapia de reidratacao oral|\btro\b|plano a|plano b", "nome": "Reidratação oral", "tipo": "conduta",
     "resumo": "diarreia sem desidratação (plano A, em casa) ou com desidratação sem gravidade (plano B, na unidade)", "pistas": [r"diarre", r"desidrat|sede|olhos fundos"]},
    {"p": r"plano c|hidratacao venosa|reidratacao venosa", "nome": "Hidratação venosa (Plano C)", "tipo": "conduta",
     "resumo": "desidratação grave (letargia, incapacidade de beber, pulso fraco)", "pistas": [r"letarg|nao consegue beber|pulso (fino|fraco)"]},
    {"p": r"zinco", "nome": "Suplementação de zinco", "tipo": "conduta",
     "resumo": "diarreia aguda em < 5 anos por 10–14 dias (reduz duração e recorrência)", "pistas": [r"diarre"]},
    {"p": r"gluconato de calcio", "nome": "Gluconato de cálcio", "tipo": "farmaco",
     "resumo": "estabiliza miocárdio na hipercalemia com alteração de ECG; antídoto da intoxicação por magnésio", "pistas": [r"potassio .*[6-9][.,]|hipercalem|onda t apiculada", r"magnesio|reflexo patelar abolido"]},
    {"p": r"hemodialise|dialise", "nome": "Diálise", "tipo": "conduta",
     "resumo": "indicações de urgência (AEIOU): acidose, eletrólitos (K refratário), intoxicações, sobrecarga de volume, uremia", "pistas": [r"uremi|pericardite", r"refratari", r"anuria"]},
    {"p": r"transfus|concentrado de hemacias|hemocomponente", "nome": "Transfusão", "tipo": "conduta",
     "resumo": "choque hemorrágico classe III/IV e anemia sintomática/Hb < 7 (limiar restritivo)", "pistas": [r"hemoglobina .*[3-6][.,]|hb [3-6]", r"hemorragia|sangramento", r"choque"]},
    {"p": r"alopurinol|febuxostat", "nome": "Hipouricemiante", "tipo": "farmaco",
     "resumo": "profilaxia de gota recorrente/tofos/nefrolitíase úrica e síndrome de lise tumoral – não iniciar na crise", "pistas": [r"acido urico|tofo"]},
    {"p": r"colchicina", "nome": "Colchicina", "tipo": "farmaco",
     "resumo": "crise de gota (início precoce), pericardite, febre familiar do Mediterrâneo", "pistas": [r"podagra|halux|monoartrit", r"pericardit"]},
    {"p": r"hidroxiureia", "nome": "Hidroxiureia", "tipo": "farmaco",
     "resumo": "anemia falciforme (aumenta HbF, reduz crises) e doenças mieloproliferativas", "pistas": [r"falciforme|crises vaso"]},
    {"p": r"imatinibe|inibidor de tirosina", "nome": "Inibidor de tirosina-quinase", "tipo": "farmaco",
     "resumo": "tratamento da LMC (BCR-ABL)", "pistas": [r"basofil", r"esplenomegal", r"philadelphia|bcr"]},
    {"p": r"vacina", "nome": "Vacinação", "tipo": "conduta",
     "resumo": "prevenção primária – seguir o Calendário Nacional; contraindicação de vacinas vivas em gestantes e imunossuprimidos graves", "pistas": [r"calendario|vacina|caderneta"]},
    # ------------------------------------------------ EXAMES
    {"p": r"eletrocardiograma|\becg\b", "nome": "Eletrocardiograma", "tipo": "exame",
     "resumo": "dor torácica (em até 10 min), arritmias, distúrbios de potássio, síncope", "pistas": [r"dor precordial|dor toracica", r"palpita|sincope", r"potassio"]},
    {"p": r"radiografia|raio-?x|rx de", "nome": "Radiografia", "tipo": "exame",
     "resumo": "exame inicial simples: tórax (pneumonia, pneumotórax), abdome (obstrução, pneumoperitônio), ossos (fratura)", "pistas": [r"tosse|febre|crepita", r"trauma|queda", r"distensao"]},
    {"p": r"ressonancia", "nome": "Ressonância magnética", "tipo": "exame",
     "resumo": "melhor para partes moles, SNC, medula, pelve; demorada e cara – não é exame inicial na urgência", "pistas": [r"medula|radicul|deficit"]},
    {"p": r"hemocultura", "nome": "Hemoculturas", "tipo": "exame",
     "resumo": "colher antes do antibiótico na sepse/endocardite, sem atrasá-lo", "pistas": [r"febre", r"sopro", r"sepse|calafrio"]},
    {"p": r"puncao lombar|liquor", "nome": "Punção lombar", "tipo": "exame",
     "resumo": "meningite/encefalite e HSA com TC normal; fazer TC antes se déficit focal, papiledema, rebaixamento ou imunossupressão", "pistas": [r"rigidez de nuca|meningit", r"febre", r"cefaleia"]},
    {"p": r"paracentese", "nome": "Paracentese diagnóstica", "tipo": "exame",
     "resumo": "ascite nova ou cirrótico com piora clínica (PBE: PMN ≥ 250/mm³)", "pistas": [r"ascite|cirro"]},
    {"p": r"beta-?hcg|teste de gravidez", "nome": "Beta-hCG", "tipo": "exame",
     "resumo": "primeiro exame em mulher em idade fértil com amenorreia, dor pélvica ou sangramento", "pistas": [r"amenorre|atraso menstrual", r"dor pelvica|sangramento vaginal"]},
    {"p": r"hemograma", "nome": "Hemograma", "tipo": "exame",
     "resumo": "anemias, infecções, leucemias, plaquetopenias", "pistas": [r"palidez|anemia", r"febre", r"petequi|sangramento"]},
    {"p": r"sorologia|teste rapido", "nome": "Sorologia / teste rápido", "tipo": "exame",
     "resumo": "triagem de HIV, sífilis, hepatites; pode ser negativa na janela imunológica", "pistas": [r"exposicao|relacao sexual|pre-?natal"]},
    # ------------------------------------------------ DIAGNÓSTICOS FREQUENTES
    {"p": r"infarto .*ventriculo direito|iam de vd", "nome": "IAM de ventrículo direito", "tipo": "dx",
     "resumo": "IAM inferior + hipotensão com pulmões limpos e turgência jugular, piora com nitrato/morfina → volume", "pistas": [r"inferior|dii, diii|avf", r"hipotens|pa cai", r"nitrato|morfina", r"jugular"]},
    {"p": r"infarto|sindrome coronariana|\biam\b|\bsca\b", "nome": "Síndrome coronariana aguda", "tipo": "dx",
     "resumo": "dor precordial em aperto com irradiação, sudorese; ECG + troponina", "pistas": [r"dor precordial|dor toracica|aperto", r"sudorese", r"supra|troponina"]},
    {"p": r"embolia pulmonar|tromboembolismo|\btep\b", "nome": "Tromboembolismo pulmonar", "tipo": "dx",
     "resumo": "dispneia súbita, dor pleurítica, taquicardia, hipoxemia em paciente com fator de risco (imobilização, cirurgia, câncer, estrogênio)", "pistas": [r"dispneia subita", r"imobil|pos-?operatorio|viagem|anticoncepcional", r"taquicard", r"panturrilha"]},
    {"p": r"pneumotorax", "nome": "Pneumotórax", "tipo": "dx",
     "resumo": "dor torácica/dispneia súbitas, MV diminuído e hipertimpanismo; hipertensivo → desvio de traqueia e choque", "pistas": [r"hipertimpan", r"murmurio .*(abolido|diminuido|ausente)", r"longilineo|tabag|trauma"]},
    {"p": r"tamponamento", "nome": "Tamponamento cardíaco", "tipo": "dx",
     "resumo": "tríade de Beck (hipotensão, turgência jugular, bulhas abafadas) e pulso paradoxal", "pistas": [r"bulhas abafadas", r"jugular", r"hipotens", r"paradoxal"]},
    {"p": r"pneumonia", "nome": "Pneumonia", "tipo": "dx",
     "resumo": "febre, tosse produtiva, dispneia, crepitações/sopro tubário e consolidação à radiografia", "pistas": [r"febre", r"tosse", r"crepita|estertor|sopro tubario", r"consolidac"]},
    {"p": r"apendicite", "nome": "Apendicite aguda", "tipo": "dx",
     "resumo": "dor periumbilical que migra para FID, anorexia, febre baixa, Blumberg positivo", "pistas": [r"fossa iliaca direita|fid|mcburney", r"anorexia|inapetencia", r"blumberg|descompressao"]},
    {"p": r"colecistite", "nome": "Colecistite aguda", "tipo": "dx",
     "resumo": "dor em hipocôndrio direito > 6h, febre, Murphy positivo, espessamento da parede da vesícula", "pistas": [r"hipocondrio direito", r"murphy", r"febre"]},
    {"p": r"colangite", "nome": "Colangite aguda", "tipo": "dx",
     "resumo": "tríade de Charcot (febre, icterícia, dor em HCD) → antibiótico + drenagem biliar", "pistas": [r"ictericia", r"febre", r"hipocondrio direito"]},
    {"p": r"pancreatite", "nome": "Pancreatite aguda", "tipo": "dx",
     "resumo": "dor epigástrica em faixa irradiada para dorso + lipase > 3x; causas: litíase biliar e álcool", "pistas": [r"faixa|dorso", r"lipase|amilase", r"etil|alcool|litias"]},
    {"p": r"gravidez ectopica|gestacao ectopica|prenhez ectopica", "nome": "Gravidez ectópica", "tipo": "dx",
     "resumo": "atraso menstrual + dor pélvica + sangramento; beta-hCG positivo sem saco intrauterino à USG", "pistas": [r"atraso menstrual|amenorre", r"dor pelvica|dor abdominal", r"beta-?hcg"]},
    {"p": r"placenta previa", "nome": "Placenta prévia", "tipo": "dx",
     "resumo": "sangramento vermelho-vivo, indolor, de repetição, com útero relaxado no 3º trimestre", "pistas": [r"indolor", r"vermelho vivo|rutilante", r"utero (relaxado|normotonic)"]},
    {"p": r"descolamento (prematuro )?(de|da) placenta|\bdpp\b", "nome": "Descolamento prematuro de placenta", "tipo": "dx",
     "resumo": "dor abdominal, hipertonia uterina, sangramento escuro, sofrimento fetal; associado a HAS e trauma", "pistas": [r"hiperton", r"dor abdominal", r"hipertens|pre-?eclamps|trauma"]},
    {"p": r"pre-?eclampsia|eclampsia|hellp", "nome": "Pré-eclâmpsia / eclâmpsia", "tipo": "dx",
     "resumo": "PA ≥ 140x90 após 20 semanas + proteinúria/lesão de órgão-alvo; convulsão = eclâmpsia; HELLP = hemólise, enzimas hepáticas ↑, plaquetas ↓", "pistas": [r"semanas", r"proteinuria", r"1[4-9]\d ?x ?(9|1[0-2])\d", r"cefaleia|escotoma|epigastr"]},
    {"p": r"diabetes (mellitus )?gestacional", "nome": "Diabetes gestacional", "tipo": "dx",
     "resumo": "jejum 92–125 mg/dL em qualquer momento ou TOTG 24–28 sem alterado (92/180/153)", "pistas": [r"glicemia", r"totg|tolerancia"]},
    {"p": r"bronquiolite", "nome": "Bronquiolite viral aguda", "tipo": "dx",
     "resumo": "lactente < 2 anos, pródromo gripal seguido de sibilância/crepitações e desconforto respiratório (VSR)", "pistas": [r"lactente|meses", r"sibil|crepita", r"coriza"]},
    {"p": r"crupe|laringotraqueobronquite|laringite", "nome": "Crupe viral", "tipo": "dx",
     "resumo": "tosse ladrante, rouquidão, estridor inspiratório; dexametasona ± adrenalina", "pistas": [r"ladrante", r"estridor", r"rouquid"]},
    {"p": r"epiglotite", "nome": "Epiglotite aguda", "tipo": "dx",
     "resumo": "início súbito, febre alta, toxemia, sialorreia, disfagia, voz abafada, posição em tripé, SEM tosse ladrante; não examinar a orofaringe nem agitar a criança – via aérea em ambiente controlado + ceftriaxona (Hib)", "pistas": [r"sialorreia|baba", r"tripe", r"toxemi", r"voz abafada", r"disfagia"]},
    {"p": r"meningite", "nome": "Meningite", "tipo": "dx",
     "resumo": "febre, cefaleia, rigidez de nuca, alteração de consciência; petéquias sugerem meningococo", "pistas": [r"rigidez de nuca", r"febre", r"petequ", r"cefaleia"]},
    {"p": r"sepse|choque septico", "nome": "Sepse / choque séptico", "tipo": "dx",
     "resumo": "infecção + disfunção orgânica; choque: vasopressor para PAM ≥ 65 e lactato > 2 apesar de volume", "pistas": [r"febre|hipotermia", r"hipotens", r"lactato", r"confus"]},
    {"p": r"dengue", "nome": "Dengue", "tipo": "dx",
     "resumo": "febre alta, mialgia, dor retro-orbitária, exantema; sinais de alarme na defervescência", "pistas": [r"retro-?orbit", r"mialgia", r"plaqueta", r"exantema"]},
    {"p": r"tuberculose", "nome": "Tuberculose", "tipo": "dx",
     "resumo": "tosse > 3 semanas, febre vespertina, sudorese noturna, emagrecimento; TRM-TB/baciloscopia", "pistas": [r"tosse .*(semanas|3 sem)", r"sudorese noturna", r"emagrec|perda de peso", r"cavita"]},
    {"p": r"sifilis", "nome": "Sífilis", "tipo": "dx",
     "resumo": "cancro duro indolor (primária), roséola/condiloma plano/lesões palmoplantares (secundária); VDRL + treponêmico", "pistas": [r"vdrl|treponem", r"palmoplantar|cancro"]},
    {"p": r"torcao testicular", "nome": "Torção testicular", "tipo": "dx",
     "resumo": "dor escrotal súbita em adolescente, testículo elevado/horizontalizado, reflexo cremastérico ausente", "pistas": [r"dor (escrotal|testicular)", r"cremaster", r"subit"]},
    {"p": r"hiperplasia prostatica|\bhpb\b", "nome": "Hiperplasia prostática benigna", "tipo": "dx",
     "resumo": "LUTS em homem idoso (jato fraco, noctúria, esforço miccional); alfa-bloqueador ± inibidor da 5-alfa-redutase", "pistas": [r"jato", r"nocturia|noctúria", r"prostata"]},
]

KB += [
    {"p": r"espondilite anquilosante|espondiloartrite axial", "nome": "Espondilite anquilosante", "tipo": "dx",
     "resumo": "homem jovem, lombalgia inflamatória > 3 meses (piora em repouso/manhã, melhora com movimento), sacroiliíte, HLA-B27; FR negativo",
     "pistas": [r"lombar|lombalgia", r"rigidez matinal", r"melhora com (o )?movimento|melhora com exercicio", r"sacroil", r"hla-?b27"]},
    {"p": r"artrite reativa|reiter", "nome": "Artrite reativa", "tipo": "dx",
     "resumo": "oligoartrite assimétrica de membros inferiores 1–4 semanas após uretrite (clamídia) ou diarreia; pode ter conjuntivite e uretrite",
     "pistas": [r"uretrite|diarreia|disenteria", r"conjuntivite", r"semanas apos"]},
    {"p": r"artrite psoriatica", "nome": "Artrite psoriática", "tipo": "dx",
     "resumo": "artrite em paciente com psoríase (pele/unhas), dactilite, acometimento de interfalangianas distais", "pistas": [r"psoria", r"unha|onic", r"dactilite|dedo em salsicha"]},
    {"p": r"lupus", "nome": "Lúpus eritematoso sistêmico", "tipo": "dx",
     "resumo": "mulher jovem, artrite não erosiva, eritema malar, fotossensibilidade, serosite, nefrite, citopenias; anti-DNA/anti-Sm",
     "pistas": [r"mulher|feminino", r"malar|fotossens", r"anti-?dna .*positiv|anti-?sm", r"proteinuria|nefrite"]},
    {"p": r"artrite reumatoide", "nome": "Artrite reumatoide", "tipo": "dx",
     "resumo": "poliartrite simétrica de pequenas articulações de mãos/punhos, rigidez matinal > 1h, FR e anti-CCP", "pistas": [r"poliartrit|maos|punhos|metacarpofalang", r"anti-?ccp .*positiv|fator reumatoide positiv"]},
    {"p": r"\bgota\b|artrite gotosa", "nome": "Gota", "tipo": "dx",
     "resumo": "monoartrite aguda muito dolorosa (podagra), cristais de urato com birrefringência negativa", "pistas": [r"halux|podagra|primeiro pododactilo", r"acido urico", r"tiazid|alcool|carne"]},
    {"p": r"pseudogota|pirofosfato|condrocalcinose", "nome": "Pseudogota (pirofosfato de cálcio)", "tipo": "dx",
     "resumo": "idoso, monoartrite de joelho/punho, cristais romboides com birrefringência positiva, condrocalcinose", "pistas": [r"joelho", r"idos", r"condrocalc"]},
    {"p": r"artrite septica", "nome": "Artrite séptica", "tipo": "dx",
     "resumo": "monoartrite aguda febril; líquido com > 50.000 leucócitos, Gram/cultura → drenagem + antibiótico", "pistas": [r"febre", r"monoartrit|joelho quente"]},
    {"p": r"fibromialgia", "nome": "Fibromialgia", "tipo": "dx",
     "resumo": "dor difusa crônica, fadiga, sono não reparador, exames normais", "pistas": [r"dor difusa|dores pelo corpo", r"sono|fadiga", r"exames normais"]},
    {"p": r"polimialgia reumatica", "nome": "Polimialgia reumática", "tipo": "dx",
     "resumo": "> 50 anos, dor e rigidez de cinturas escapular e pélvica, VHS alto; associada à arterite de células gigantes", "pistas": [r"cintura|ombros|quadril", r"vhs|pcr", r"[5-9]\d anos"]},
    {"p": r"arterite (temporal|de celulas gigantes)", "nome": "Arterite de células gigantes", "tipo": "dx",
     "resumo": "idoso com cefaleia nova, claudicação de mandíbula, alteração visual, VHS alto → corticoide imediato", "pistas": [r"cefaleia", r"mandibula", r"visual|amaurose", r"vhs"]},
    {"p": r"blefarite", "nome": "Blefarite", "tipo": "dx", "resumo": "inflamação da borda palpebral com crostas; principal agente S. aureus; higiene palpebral", "pistas": [r"palpebra|borda", r"crost"]},
    {"p": r"staphylococcus aureus", "nome": "Staphylococcus aureus", "tipo": "dx",
     "resumo": "principal agente de blefarite, impetigo bolhoso, celulite purulenta, abscessos, mastite, osteomielite e artrite séptica", "pistas": [r"crost|purulent|abscess|palpebra|mastite|osteomiel"]},
    {"p": r"conjuntivite", "nome": "Conjuntivite", "tipo": "dx", "resumo": "olho vermelho com secreção; viral (adenovírus, aquosa, linfonodo pré-auricular), bacteriana (purulenta), alérgica (prurido)", "pistas": [r"hiperemia conjuntival|olho vermelho", r"secrec"]},
    {"p": r"hipotireoidismo", "nome": "Hipotireoidismo", "tipo": "dx", "resumo": "fadiga, ganho de peso, intolerância ao frio, constipação, bradicardia; TSH alto e T4L baixo", "pistas": [r"frio", r"ganho de peso", r"constip", r"tsh"]},
    {"p": r"cetoacidose", "nome": "Cetoacidose diabética", "tipo": "dx", "resumo": "hiperglicemia, acidose metabólica com ânion gap alto e cetonemia; hidratação, insulina, potássio", "pistas": [r"glicemia .*[3-9]\d\d", r"kussmaul|halito", r"ph .*7[.,][0-2]|bicarbonato"]},
    {"p": r"insuficiencia cardiaca", "nome": "Insuficiência cardíaca", "tipo": "dx", "resumo": "dispneia, ortopneia, edema, turgência jugular, B3, crepitações; ecocardiograma define a FE", "pistas": [r"dispneia|ortopneia", r"edema", r"b3", r"jugular"]},
    {"p": r"dpoc|doenca pulmonar obstrutiva", "nome": "DPOC", "tipo": "dx", "resumo": "tabagista com dispneia progressiva, tosse crônica; VEF1/CVF < 0,70 pós-BD", "pistas": [r"tabag|macos", r"dispneia", r"tosse"]},
    {"p": r"\basma\b", "nome": "Asma", "tipo": "dx", "resumo": "sibilância episódica, tosse noturna, gatilhos, reversibilidade ao broncodilatador", "pistas": [r"sibil", r"noturn", r"atopia|rinite"]},
    {"p": r"hanseniase", "nome": "Hanseníase", "tipo": "dx", "resumo": "mancha/placa com alteração de sensibilidade, espessamento neural; PQT-U", "pistas": [r"sensibilidade", r"mancha", r"nervo"]},
    {"p": r"escabiose|sarna", "nome": "Escabiose", "tipo": "dx", "resumo": "prurido noturno intenso, lesões em interdígitos, punhos, cintura; contactantes afetados; ivermectina/permetrina + tratar todos + lavar roupas", "pistas": [r"prurido", r"noturn", r"cela|domicilio|contatos|familia"]},
    {"p": r"ivermectina|permetrina", "nome": "Ivermectina / permetrina", "tipo": "farmaco", "resumo": "tratamento da escabiose e pediculose; ivermectina repetida após 7–14 dias; tratar contactantes simultaneamente", "pistas": [r"prurido", r"noturn"]},
    {"p": r"hepatite a\b|anti-?hav", "nome": "Hepatite A", "tipo": "dx", "resumo": "transmissão fecal-oral, surtos em escolas/creches; IgM anti-HAV; notificação de surto", "pistas": [r"ictericia", r"escola|creche", r"esgoto|agua"]},
    {"p": r"amitriptilina|triciclic", "nome": "Amitriptilina", "tipo": "farmaco", "resumo": "profilaxia de enxaqueca (útil com insônia), dor neuropática; efeitos anticolinérgicos, evitar em idosos e cardiopatas", "pistas": [r"enxaqueca|migranea|cefaleia", r"insonia"]},
    {"p": r"propranolol|propanolol", "nome": "Propranolol", "tipo": "farmaco", "resumo": "betabloqueador não seletivo: profilaxia de enxaqueca, tremor essencial, varizes; contraindicado em asma/broncoespasmo", "pistas": [r"enxaqueca|tremor|varizes"]},
    {"p": r"sumatriptano|triptano", "nome": "Triptano", "tipo": "farmaco", "resumo": "tratamento da CRISE de enxaqueca (não profilaxia); contraindicado em doença coronariana", "pistas": [r"crise"]},
]

KB += [
    {"p": r"toracocentese", "nome": "Toracocentese", "tipo": "conduta",
     "resumo": "punção do derrame pleural: diagnóstica (critérios de Light, pH, glicose, Gram) e terapêutica; derrame parapneumônico complicado/empiema → drenagem",
     "pistas": [r"derrame pleural", r"macicez", r"murmurio .*(abolido|diminuido)", r"pneumonia|consolidac"]},
    {"p": r"derrame pleural", "nome": "Derrame pleural", "tipo": "dx", "resumo": "macicez, MV e frêmito diminuídos; transudato × exsudato pelos critérios de Light", "pistas": [r"macicez", r"frêmito|fremito"]},
    {"p": r"baar|baciloscopia|escarro", "nome": "Baciloscopia/exame de escarro", "tipo": "exame",
     "resumo": "investigação de tuberculose (tosse ≥ 3 semanas, febre vespertina, sudorese noturna, emagrecimento); TRM-TB é preferencial", "pistas": [r"tosse .*(semanas|3 sem)", r"sudorese noturna", r"emagrec"]},
]
