-- CTI v16 — usuários e auditoria persistentes
-- Execute este arquivo UMA vez no SQL Editor do projeto Supabase exclusivo do CTI.
-- A aplicação acessa estas tabelas apenas pelo backend usando uma Secret Key.

begin;

create table if not exists public.cti_users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  username_norm text not null,
  password_hash text not null,
  role text not null default 'user' check (role in ('admin','user')),
  active boolean not null default true,
  session_version integer not null default 1 check (session_version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz,
  password_changed_at timestamptz,
  deleted_at timestamptz
);

create unique index if not exists cti_users_username_norm_active_uq
  on public.cti_users (username_norm)
  where deleted_at is null;

create index if not exists cti_users_active_role_idx
  on public.cti_users (active, role)
  where deleted_at is null;

create index if not exists cti_users_last_login_idx
  on public.cti_users (last_login_at desc nulls last)
  where deleted_at is null;

create or replace function public.cti_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_cti_users_updated_at on public.cti_users;
create trigger trg_cti_users_updated_at
before update on public.cti_users
for each row execute function public.cti_set_updated_at();

create table if not exists public.cti_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  actor_username text,
  action text not null,
  target_user_id uuid,
  target_username text,
  ip_fingerprint text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists cti_audit_created_at_idx
  on public.cti_audit_log (created_at desc);

create index if not exists cti_audit_actor_idx
  on public.cti_audit_log (actor_user_id, created_at desc);

-- Defesa em profundidade: clientes anon/authenticated não leem nem escrevem estas tabelas.
alter table public.cti_users enable row level security;
alter table public.cti_audit_log enable row level security;

revoke all on table public.cti_users from anon, authenticated;
revoke all on table public.cti_audit_log from anon, authenticated;
grant all on table public.cti_users to service_role;
grant all on table public.cti_audit_log to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
